policies:
  - name: redshift-cluster-maintenancesettings-check
    resource: redshift
    filters:
     - or:
        - type: value
          key: AutomatedSnapshotRetentionPeriod
          value: 0
        - type: value
          key: AllowVersionUpgrade
          value: false